# Generated by Django 4.2.5 on 2024-04-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
