# Generated by Django 4.2.5 on 2024-04-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
