# Generated by Django 4.2.5 on 2024-04-29 14:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0006_product_is_ordered'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('user', 'product')},
        ),
    ]
