# Generated by Django 4.2.5 on 2024-04-29 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_purchaseorder_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.product', unique=True),
        ),
    ]
