# Generated by Django 5.0.2 on 2024-09-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_restockedproduct_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('breed_recommendations', models.TextField()),
                ('side_effects', models.TextField()),
            ],
        ),
    ]
