# Generated by Django 5.0.2 on 2024-09-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0017_medicine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
