# Generated by Django 5.0.2 on 2024-10-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0024_appointment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=9),
        ),
        migrations.AddField(
            model_name='doctor',
            name='end_time',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
